// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: scanner.jflex

import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\0"+
    "\1\5\1\6\4\0\1\7\1\10\1\11\1\0\1\12"+
    "\1\13\1\0\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\3\24\1\25\1\26\34\0\1\27\1\30"+
    "\7\0\2\31\2\0\1\32\1\0\1\33\3\0\1\34"+
    "\3\0\1\35\2\0\1\36\2\0\1\37\5\0\1\40"+
    "\1\0\1\41\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\3\1\1\3\1\1\1\4\1\5"+
    "\1\6\4\1\1\7\1\10\1\0\1\11\7\0\1\12"+
    "\11\0\1\13\2\14\5\0\1\15\25\0\1\16\15\0"+
    "\1\17\36\0\1\20\1\0\1\20\2\0\2\20\2\0"+
    "\2\20\1\17\2\0\1\20\16\0\1\20\1\0\1\20"+
    "\1\0\2\20\1\0\2\20\2\0\1\20\50\0\1\20"+
    "\1\0\6\20";

  private static int [] zzUnpackAction() {
    int [] result = new int[201];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\42\0\104\0\146\0\210\0\252\0\42"+
    "\0\314\0\356\0\42\0\42\0\u0110\0\u0132\0\u0154\0\u0176"+
    "\0\42\0\42\0\146\0\42\0\u0198\0\u01ba\0\u01dc\0\u01fe"+
    "\0\u0220\0\u0242\0\u0264\0\42\0\u0286\0\u02a8\0\u02ca\0\u02ec"+
    "\0\u030e\0\u0330\0\u0352\0\u0374\0\u0396\0\42\0\42\0\u02ec"+
    "\0\u03b8\0\u03da\0\u03fc\0\u041e\0\u0440\0\u0462\0\u0484\0\u04a6"+
    "\0\u04c8\0\u04ea\0\u050c\0\u052e\0\u0550\0\u0572\0\u0594\0\u05b6"+
    "\0\u05d8\0\u05fa\0\u061c\0\u063e\0\u0660\0\u0682\0\u06a4\0\u06c6"+
    "\0\u06e8\0\u070a\0\u072c\0\42\0\u074e\0\u0770\0\u0792\0\u07b4"+
    "\0\u07d6\0\u07f8\0\u081a\0\u083c\0\u085e\0\u0880\0\u08a2\0\u08c4"+
    "\0\u08e6\0\u0908\0\u092a\0\u094c\0\u096e\0\u0990\0\u09b2\0\u09d4"+
    "\0\u09f6\0\u0a18\0\u0a3a\0\u0a5c\0\u0a7e\0\u0aa0\0\u0ac2\0\u0ae4"+
    "\0\u0b06\0\u0b28\0\u0b4a\0\u0b6c\0\u0b8e\0\u0bb0\0\u0bd2\0\u0bf4"+
    "\0\u0c16\0\u0c38\0\u0c5a\0\u0c7c\0\u0c9e\0\u0cc0\0\u0ce2\0\u0d04"+
    "\0\u0d26\0\u0d48\0\u0d6a\0\u0d8c\0\u0dae\0\u0dd0\0\u0df2\0\u0e14"+
    "\0\u0e36\0\u0e58\0\u0e7a\0\u0c5a\0\u0e9c\0\u0ebe\0\u0ee0\0\u0f02"+
    "\0\u0f24\0\u0f46\0\u0f68\0\u0f8a\0\u0fac\0\u0fce\0\u0ff0\0\u1012"+
    "\0\u1034\0\u1056\0\u1078\0\u109a\0\u10bc\0\u10de\0\u1100\0\u1122"+
    "\0\u1144\0\u1166\0\u1188\0\u11aa\0\u11cc\0\u11ee\0\u1210\0\u1232"+
    "\0\u1254\0\u1276\0\u1298\0\u12ba\0\u12dc\0\u12fe\0\u1320\0\u1342"+
    "\0\u1364\0\u1386\0\u13a8\0\u13ca\0\u13ec\0\u140e\0\u1430\0\u1452"+
    "\0\u1474\0\u1496\0\u14b8\0\u14da\0\u14fc\0\u151e\0\u1540\0\u1562"+
    "\0\u1584\0\u15a6\0\u15c8\0\u15ea\0\u160c\0\u162e\0\u1650\0\u1672"+
    "\0\u1694\0\u16b6\0\u16d8\0\u16fa\0\u171c\0\u173e\0\u1760\0\u1782"+
    "\0\u17a4\0\u17c6\0\u17e8\0\u17e8\0\u180a\0\u182c\0\u184e\0\u1870"+
    "\0\42";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[201];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\2\2"+
    "\1\10\2\2\1\11\7\12\1\13\1\14\1\15\1\16"+
    "\1\2\1\17\1\2\1\20\3\2\1\21\1\22\44\0"+
    "\1\3\37\0\5\23\1\24\34\23\6\0\1\25\44\0"+
    "\1\26\30\0\2\27\3\0\10\27\10\30\17\27\3\0"+
    "\10\27\10\12\15\27\13\0\1\31\41\0\1\32\65\0"+
    "\1\33\35\0\1\34\14\0\1\35\33\0\11\26\1\36"+
    "\30\26\15\0\10\37\15\0\2\27\3\0\10\27\10\40"+
    "\15\27\15\0\1\41\1\42\1\43\40\0\1\44\61\0"+
    "\1\45\11\0\1\46\33\0\10\26\1\3\1\36\30\26"+
    "\15\0\10\47\15\0\2\27\3\0\10\27\10\50\15\27"+
    "\20\0\1\51\4\52\32\0\10\52\32\0\3\52\1\53"+
    "\36\0\1\54\1\55\60\0\1\56\31\0\1\57\41\0"+
    "\1\60\41\0\1\61\31\0\1\62\1\63\40\0\1\64"+
    "\1\65\37\0\1\66\47\0\1\67\34\0\6\70\34\0"+
    "\4\70\1\71\35\0\2\65\36\0\1\72\1\0\1\73"+
    "\1\74\40\0\2\74\36\0\1\72\1\0\2\74\57\0"+
    "\1\75\23\0\1\76\6\77\32\0\10\77\32\0\5\77"+
    "\1\100\35\0\1\101\36\0\1\72\1\0\1\102\1\103"+
    "\36\0\1\72\1\0\2\103\56\0\1\104\33\0\1\105"+
    "\41\0\1\106\41\0\1\107\31\0\1\110\1\111\36\0"+
    "\1\72\1\0\1\103\1\112\36\0\1\72\1\0\2\112"+
    "\44\0\1\113\1\114\34\0\6\114\34\0\3\114\1\115"+
    "\36\0\1\116\1\117\40\0\1\120\1\121\36\0\1\72"+
    "\52\0\1\122\32\0\10\122\32\0\5\122\35\0\2\121"+
    "\36\0\1\123\1\0\1\124\1\125\40\0\2\125\36\0"+
    "\1\123\1\0\2\125\54\0\1\126\26\0\1\127\36\0"+
    "\1\123\1\0\1\130\1\131\36\0\1\123\1\0\2\131"+
    "\54\0\1\132\25\0\1\133\1\134\36\0\1\123\1\0"+
    "\1\131\1\135\36\0\1\123\1\0\2\135\54\0\1\136"+
    "\25\0\1\137\1\140\40\0\1\141\1\142\36\0\1\123"+
    "\57\0\1\143\25\0\2\142\36\0\1\144\1\0\1\145"+
    "\1\146\40\0\2\146\36\0\1\144\1\0\2\146\54\0"+
    "\1\147\26\0\1\150\36\0\1\144\1\0\1\151\1\152"+
    "\36\0\1\144\1\0\2\152\54\0\1\153\25\0\1\154"+
    "\1\155\36\0\1\144\1\0\1\152\1\156\36\0\1\144"+
    "\1\0\2\156\54\0\1\157\25\0\1\160\1\161\40\0"+
    "\1\162\1\163\36\0\1\144\57\0\1\164\25\0\2\163"+
    "\36\0\1\165\1\0\1\166\1\167\40\0\2\167\36\0"+
    "\1\165\1\0\2\167\54\0\1\170\26\0\1\171\36\0"+
    "\1\165\1\0\1\172\1\173\36\0\1\165\1\0\2\173"+
    "\54\0\1\174\25\0\1\175\1\176\36\0\1\165\1\0"+
    "\1\173\1\177\36\0\1\165\1\0\2\177\40\0\1\200"+
    "\1\201\40\0\1\202\1\203\36\0\1\165\43\0\2\203"+
    "\36\0\1\204\1\0\1\205\1\206\40\0\2\206\36\0"+
    "\1\204\1\0\2\206\41\0\1\207\36\0\1\204\1\0"+
    "\1\210\1\211\36\0\1\204\1\0\2\211\40\0\1\212"+
    "\1\213\36\0\1\204\1\0\1\211\1\214\36\0\1\204"+
    "\1\0\2\214\40\0\1\215\1\216\40\0\1\217\1\220"+
    "\36\0\1\204\43\0\2\220\36\0\1\221\1\0\1\222"+
    "\1\223\40\0\2\223\36\0\1\221\1\0\2\223\41\0"+
    "\1\224\36\0\1\221\1\0\1\225\1\226\36\0\1\221"+
    "\1\0\2\226\40\0\1\227\1\230\36\0\1\221\1\0"+
    "\1\226\1\231\36\0\1\221\1\0\2\231\40\0\1\232"+
    "\1\233\40\0\1\234\1\235\36\0\1\221\43\0\2\235"+
    "\36\0\1\236\1\0\1\237\1\240\40\0\2\240\36\0"+
    "\1\236\1\0\2\240\41\0\1\241\36\0\1\236\1\0"+
    "\1\242\1\243\36\0\1\236\1\0\2\243\40\0\1\244"+
    "\1\245\36\0\1\236\1\0\1\243\1\246\36\0\1\236"+
    "\1\0\2\246\40\0\1\247\1\250\40\0\1\251\1\252"+
    "\36\0\1\236\43\0\2\252\36\0\1\253\1\0\1\254"+
    "\1\255\40\0\2\255\36\0\1\253\1\0\2\255\41\0"+
    "\1\256\36\0\1\253\1\0\1\257\1\260\36\0\1\253"+
    "\1\0\2\260\40\0\1\261\1\262\36\0\1\253\1\0"+
    "\1\260\1\263\36\0\1\253\1\0\2\263\40\0\1\264"+
    "\1\265\40\0\1\266\1\267\36\0\1\253\43\0\2\267"+
    "\36\0\1\270\1\0\1\271\1\272\40\0\2\272\36\0"+
    "\1\270\1\0\2\272\41\0\1\273\36\0\1\270\1\0"+
    "\1\274\1\275\36\0\1\270\1\0\2\275\40\0\1\276"+
    "\1\277\36\0\1\270\1\0\1\275\1\300\36\0\1\270"+
    "\1\0\2\300\40\0\1\301\1\302\40\0\1\303\1\304"+
    "\36\0\1\270\43\0\2\304\40\0\1\305\1\306\40\0"+
    "\2\306\40\0\1\307\1\310\40\0\2\310\40\0\1\310"+
    "\1\311\40\0\2\311\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6290];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\1\11\2\1\2\11\4\1\2\11"+
    "\1\0\1\11\7\0\1\11\11\0\2\11\1\1\5\0"+
    "\1\1\25\0\1\11\15\0\1\1\36\0\1\1\1\0"+
    "\1\1\2\0\2\1\2\0\3\1\2\0\1\1\16\0"+
    "\1\1\1\0\1\1\1\0\2\1\1\0\2\1\2\0"+
    "\1\1\50\0\1\1\1\0\5\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[201];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol sym(int type){
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol sym(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Scanner Error: " + yytext());
            }
            // fall through
          case 17: break;
          case 2:
            { ;
            }
            // fall through
          case 18: break;
          case 3:
            { return sym(sym.CM);
            }
            // fall through
          case 19: break;
          case 4:
            { return sym(sym.INUM, new Integer(yytext()));
            }
            // fall through
          case 20: break;
          case 5:
            { return sym(sym.CO);
            }
            // fall through
          case 21: break;
          case 6:
            { return sym(sym.SC);
            }
            // fall through
          case 22: break;
          case 7:
            { return sym(sym.OC);
            }
            // fall through
          case 23: break;
          case 8:
            { return sym(sym.CC);
            }
            // fall through
          case 24: break;
          case 9:
            { return sym(sym.QSTRING, new String(yytext()));
            }
            // fall through
          case 25: break;
          case 10:
            { return sym(sym.KG_WD, new String(yytext()));
            }
            // fall through
          case 26: break;
          case 11:
            { return sym(sym.SEP);
            }
            // fall through
          case 27: break;
          case 12:
            { return sym(sym.FNUM, new Float(yytext()));
            }
            // fall through
          case 28: break;
          case 13:
            { return sym(sym.EURO_WD, new String(yytext()));
            }
            // fall through
          case 29: break;
          case 14:
            { return sym(sym.EK_WD, new String(yytext()));
            }
            // fall through
          case 30: break;
          case 15:
            { return sym(sym.TOK1);
            }
            // fall through
          case 31: break;
          case 16:
            { return sym(sym.TOK2);
            }
            // fall through
          case 32: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
