
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUS_WD = 16;
  public static final int CP = 8;
  public static final int KWH_WD = 13;
  public static final int OP = 7;
  public static final int MAX_WD = 15;
  public static final int DONE_WD = 21;
  public static final int FUE_WD = 12;
  public static final int SCOLON = 5;
  public static final int LIT_WD = 14;
  public static final int DO_WD = 20;
  public static final int KM_WD = 22;
  public static final int USE_WD = 19;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int START_WD = 10;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int error = 1;
  public static final int UKM_WD = 23;
  public static final int BAT_WD = 11;
  public static final int DASH = 6;
  public static final int FNUM = 24;
  public static final int MOD_WD = 18;
  public static final int STAR_WD = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "SCOLON",
  "DASH",
  "OP",
  "CP",
  "COMMA",
  "START_WD",
  "BAT_WD",
  "FUE_WD",
  "KWH_WD",
  "LIT_WD",
  "MAX_WD",
  "PLUS_WD",
  "STAR_WD",
  "MOD_WD",
  "USE_WD",
  "DO_WD",
  "DONE_WD",
  "KM_WD",
  "UKM_WD",
  "FNUM"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[16]=new String("PLUS_WD");
		TT[8]=new String("CP");
		TT[13]=new String("KWH_WD");
		TT[7]=new String("OP");
		TT[15]=new String("MAX_WD");
		TT[21]=new String("DONE_WD");
		TT[12]=new String("FUE_WD");
		TT[5]=new String("SCOLON");
		TT[14]=new String("LIT_WD");
		TT[20]=new String("DO_WD");
		TT[22]=new String("KM_WD");
		TT[19]=new String("USE_WD");
		TT[9]=new String("COMMA");
		TT[0]=new String("EOF");
		TT[10]=new String("START_WD");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[1]=new String("error");
		TT[23]=new String("UKM_WD");
		TT[11]=new String("BAT_WD");
		TT[6]=new String("DASH");
		TT[24]=new String("FNUM");
		TT[18]=new String("MOD_WD");
		TT[17]=new String("STAR_WD");
	}
public String getTT(int i){return TT[i];}
}

