
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CT = 8;
  public static final int OT = 7;
  public static final int CP = 12;
  public static final int ARR = 18;
  public static final int OR = 13;
  public static final int CM = 9;
  public static final int M_WD = 20;
  public static final int OP = 11;
  public static final int S = 6;
  public static final int INUM = 21;
  public static final int COL = 14;
  public static final int EOF = 0;
  public static final int MS_WD = 16;
  public static final int TOK3 = 5;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int error = 1;
  public static final int EQ = 10;
  public static final int QSTRING = 15;
  public static final int PRINTMM = 17;
  public static final int PART = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "S",
  "OT",
  "CT",
  "CM",
  "EQ",
  "OP",
  "CP",
  "OR",
  "COL",
  "QSTRING",
  "MS_WD",
  "PRINTMM",
  "ARR",
  "PART",
  "M_WD",
  "INUM"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("CT");
		TT[7]=new String("OT");
		TT[12]=new String("CP");
		TT[18]=new String("ARR");
		TT[13]=new String("OR");
		TT[9]=new String("CM");
		TT[20]=new String("M_WD");
		TT[11]=new String("OP");
		TT[6]=new String("S");
		TT[21]=new String("INUM");
		TT[14]=new String("COL");
		TT[0]=new String("EOF");
		TT[16]=new String("MS_WD");
		TT[5]=new String("TOK3");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[1]=new String("error");
		TT[10]=new String("EQ");
		TT[15]=new String("QSTRING");
		TT[17]=new String("PRINTMM");
		TT[19]=new String("PART");
	}
public String getTT(int i){return TT[i];}
}

